# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\"\xb7\x01\n\tUeMetrics\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0b\n\x03\x63qi\x18\x02 \x01(\r\x12\x0b\n\x03snr\x18\x03 \x01(\x02\x12\x10\n\x08tx_bytes\x18\x04 \x01(\x02\x12\x10\n\x08rx_bytes\x18\x05 \x01(\x02\x12\x11\n\tdl_buffer\x18\x06 \x01(\r\x12\x11\n\tul_buffer\x18\x07 \x01(\r\x12\x0e\n\x06\x64l_tbs\x18\x08 \x01(\x02\x12\x18\n\x0bul_harq_ack\x18\x14 \x01(\x08H\x00\x88\x01\x01\x42\x0e\n\x0c_ul_harq_ack\":\n\x07Metrics\x12\x0f\n\x07tti_cnt\x18\x01 \x01(\r\x12\x1e\n\nue_metrics\x18\x02 \x03(\x0b\x32\n.UeMetricsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UEMETRICS._serialized_start=18
  _UEMETRICS._serialized_end=201
  _METRICS._serialized_start=203
  _METRICS._serialized_end=261
# @@protoc_insertion_point(module_scope)
